### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by Nystrex**

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, but these are all questions of style rather than mistakes, and in 2/3 cases I like what's already there better. I'd accept 'command-line' over 'command line' if you want to make a PR for that alone, though even there it's not really a typo.

(Just in case you're motivated by seeing that this is one of the qualifying repositories for the Mars helicopter badge, I don't think new contributrors will get the badge. I believe Github only looked at commits before the badge was created.)

**Comment by Nystrex** [comment]
> (Just in case you're motivated by seeing that this is one of the qualifying repositories for the Mars helicopter badge, I don't think new contributrors will get the badge. I believe Github only looked at commits before the badge was created.)

Hahaha, yeah I tried to cheat the system, thanks for clarifying that the badge isn't available for new contributors. 😅

**Comment by takluyver** [comment]
Yeah, I wouldn't be surprised if the Hacktoberfest snafu fed into their thinking about how to manage the badges, awarding them only based on commits before the badge was created.

It's not a great way to reward people - it's easy to miss out hidden dependencies (like pip itself, which is mentioned in the fprime install docs), and if they make badges more often, it might just lead to people spraying low-effort PRs around many different repositories in the hope of picking up future badges. But I won't deny that the Mars helicopter badge is a pretty cool thing to get. :smile:

**Comment by Red-M** [comment]
I think its less about reward and about showing who actually makes contributions.
I know this will sound cheesy but, the reward is knowing you helped out to make things just a little bit better for other people.
Its a bad reward because its not a reward and its recognising people who put the effort in when no one is asking for it (although the pip devs/contributors missing out is a little strange :( ).

Anyway, for anyone else reading this, OSS is great and people should take (more of) an interest (there are people behind those weird credits in your iP(od|hone))!

**Pull request closed without merging**
