### PR TITLE
Use setuptools, not distutils

### PR DESCRIPTION
**Pull request by njwhite**
To make wheel-building easier (see [this](http://stackoverflow.com/a/27868004/42543)).

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, but I avoid setuptools if at all possible.

**Comment by njwhite** [comment]
Hm, OK. Could you possibly put wheels up on pypi as well as the source zips? Thanks -

**Comment by takluyver** [comment]
I'll look into it.

**Comment by takluyver** [comment]
Have a look at #29.

**Comment by takluyver** [comment]
One wheel on PyPI :-)

**Comment by njwhite** [comment]
@takluyver thanks!

**Pull request closed without merging**
