### PR TITLE
rename the documentation theme to 'classic' since that is what Sphinx calls it now

### PR DESCRIPTION
**Pull request by peterph**

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, but the docs actually end up built with the Readthedocs theme, and I don't want to break that:
http://ptyprocess.readthedocs.org/en/latest/

**Comment by takluyver** [comment]
Thanks, but the docs actually end up built with the Readthedocs theme, and I don't want to break that:
http://ptyprocess.readthedocs.org/en/latest/

**Comment by peterph** [comment]
Oh, ok, thanks. Is it ok to have `pygments_style = 'sphinx'` in `conf.py` in that case? - Just wondering, I have really no idea...

**Comment by takluyver** [comment]
I'm not sure why you think that might be a problem, but I'm pretty sure it isn't ;-)

**Comment by peterph** [comment]
My complete misunderstanding of the whole docs generation thing, I guess. :)

**Pull request closed without merging**
