### PR TITLE
Integrate unicode support into PtyProcess class

### PR DESCRIPTION
**Pull request by takluyver**
Deprecating PtyProcessUnicode.

This branch will be required for similar experimentation I'm about to do in Pexpect.

### CODE REVIEW

**Comment by jquast** [comment]
+1 good.

**Comment by takluyver** [comment]
I'm actually less sure that this makes sense. I thought it was necessary to do this in order to make a similar change in Pexpect, but now I don't think it is.

In Pexpect, the equivalent change is good because we were trying to use the type system for two orthogonal sets of alternatives: bytes/unicode and pty/fd/ssh/subprocess. PtyProcess doesn't have that orthogonality problem, and I don't see any obvious reason why it would grow one. So it seems neater to actually use the type system for bytes/unicode.

**Comment by takluyver** [comment]
I think I'm now 65% in favour of leaving these as separate classes in ptyprocess, and only making the equivalent change in Pexpect. @jquast , do you have a preference about this?

**Comment by jquast** [comment]
I **really like** the ``encoding=None`` or ``encoding='utf8'`` argument for pexpect 4.0, there is no doubt there. As for ptyprocess, I'm not particular either.  I guess we can leave it as-is and drop this PR, It would only win us congruity but break any existing ptyprocess dependencies.

**Comment by takluyver** [comment]
OK, dropping this PR for now.

**Pull request closed without merging**
